apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: as-proyecto
  description: Servicio principal del proyecto AS_Proyecto
  annotations:
    github.com/project-slug: andonigarcia240/BackstageDemo_ASProyecto
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: as-proyecto
spec:
  type: service
  lifecycle: experimental
  owner: guest
  providesApis:
    - as-proyecto-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: as-proyecto-api
  description: OpenAPI del proyecto AS_Proyecto
spec:
  type: openapi
  lifecycle: experimental
  owner: guest
  definition:
    $text: http://localhost:3001/openapi.json
